/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./**/*.liquid'],
  theme: {
    extend: {
      colors: {
        beige: '#E1D0BD',
        blueDark: '#023049',
        blueLight: '#669bbc',
        beige: '#fdf0d5',
        red: '#bd1622',
        rouge: '#bd1622',
        redDark: '#7a0002',
        grayLight: '#F6F6F6',
        rose: '#C38383',
        vert: '#686856',
        jaune: '#F4BF6F',
        bleu: '#4B74C8',
        'bleu-marine': '#243149',
        gris: '#71686B',
        marron: '#6A5557',
        noir: '#000',
        orange: '#ff5f00',
      },
    },
  },
  safelist: [
    'bg-beige',
    'border-beige',
    'bg-rouge',
    'border-rouge',
    'bg-vert',
    'border-vert',
    'bg-rose',
    'border-rose',
    'bg-jaune',
    'border-jaune',
    'bg-bleu-marine',
    'border-bleu-marine',
    'bg-bleu',
    'border-bleu',
    'bg-gris',
    'border-gris',
    'bg-marron',
    'border-marron',
    'bg-noir',
    'border-noir',
    'bg-vert',
    'border-vert',
    'bg-orange',
    'border-orange',
  ],
  plugins: [],
};
